### ISSUE TITLE
listing as a reporting tool in Dataverse Admin Guide

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Report#1]
This tool isn't mentioned at http://guides.dataverse.org/en/4.15.1/admin/reporting-tools.html

Should it be? Thanks! 😄

**Comment by kaitlinnewson** [comment]
Hi @pdurbin, I see that this is listed, which is the front end tool that goes with this repo: https://github.com/scholarsportal/Dataverse-Web-Report

I'll try to make this more clear in the README!

**Comment by pdurbin** [comment]
@kaitlinnewson the change you made to the README in https://github.com/scholarsportal/Dataverse-Web-Report/commit/82fa239babf469e0e7f68781ff9ac25371726b2b helps a lot! Thanks! Closing. 😄
